# Generated by Django 3.2.16 on 2023-02-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('made_by', models.CharField(max_length=200)),
                ('made_date', models.DateField(blank=True, null=True)),
                ('best_before', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='methodic',
            name='acts_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='methodic',
            name='acts_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='methodic',
            name='used_reagents',
            field=models.ManyToManyField(related_name='methodic', to='lab.Reagent'),
        ),
    ]
