# Generated by Django 3.2.16 on 2023-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20230203_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodic',
            name='used_reagents',
            field=models.ManyToManyField(blank=True, related_name='methodic', to='lab.Reagent'),
        ),
    ]
